[package]
name = "mas/sigma"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
React = "jsdotlua/react@17.1.0"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"

Knit = "sleitnick/knit@1.7.0"
Trove = "sleitnick/trove@1.3.0"
TableUtil = "sleitnick/table-util@1.2.1"
Signal = "sleitnick/signal@2.0.1"

Promise = "evaera/promise@4.0.0"